/* This file is generated by Smudge. Do not edit it. */
#ifndef __test_smear_waits_h__
#define __test_smear_waits_h__
typedef struct test_event_t test_event_t;

typedef struct test_Event_Wrapper
{
    enum
    {
        EVID_test_event
    } id;
    union
    {
        const test_event_t *e_event;
    } event;
} test_Event_Wrapper;

void test_event(const test_event_t *);

const char *test_Current_state_name(void);

void test_Free_Message(test_Event_Wrapper);

void test_Handle_Message(test_Event_Wrapper);
#endif
